[2023-07-26 01:27:04,271] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-26T01:27:02.544758+00:00 [queued]>
[2023-07-26 01:27:04,280] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-26T01:27:02.544758+00:00 [queued]>
[2023-07-26 01:27:04,281] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:27:04,282] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 01:27:04,282] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:27:04,293] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-26 01:27:02.544758+00:00
[2023-07-26 01:27:04,298] {standard_task_runner.py:52} INFO - Started process 75 to run task
[2023-07-26 01:27:04,301] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'manual__2023-07-26T01:27:02.544758+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp6wrfjdgz', '--error-file', '/tmp/tmp1eh7ytt1']
[2023-07-26 01:27:04,303] {standard_task_runner.py:80} INFO - Job 4: Subtask fetch_exchange_rates_task
[2023-07-26 01:27:04,370] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-26T01:27:02.544758+00:00 [running]> on host 6e11a261c833
[2023-07-26 01:27:04,422] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T01:27:02.544758+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T01:27:02.544758+00:00
[2023-07-26 01:27:04,849] {logging_mixin.py:115} INFO - Save a new table exchange_latest_BTC.csv
[2023-07-26 01:27:04,870] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 78, in fetch_exchange_rates
    cur.execute(create_table_query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(exchange_rates_btc, 2200) already exists.

[2023-07-26 01:27:04,881] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230726T012702, start_date=20230726T012704, end_date=20230726T012704
[2023-07-26 01:27:04,891] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task fetch_exchange_rates_task (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(exchange_rates_btc, 2200) already exists.
; 75)
[2023-07-26 01:27:04,915] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 01:27:04,942] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
