[2023-07-25 20:34:35,265] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-25 20:34:35,277] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-25 20:34:35,278] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:35,280] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:34:35,281] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:35,297] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:00:00+00:00
[2023-07-25 20:34:35,303] {standard_task_runner.py:52} INFO - Started process 8777 to run task
[2023-07-25 20:34:35,314] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmplx74nc8j', '--error-file', '/tmp/tmpcjztcvka']
[2023-07-25 20:34:35,316] {standard_task_runner.py:80} INFO - Job 92: Subtask fetch_exchange_rates_task
[2023-07-25 20:34:35,401] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:34:35,483] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:00:00+00:00
[2023-07-25 20:34:37,391] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:34:37,432] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T000000, start_date=20230725T203435, end_date=20230725T203437
[2023-07-25 20:34:37,481] {standard_task_runner.py:97} ERROR - Failed to execute job 92 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 8777)
[2023-07-25 20:34:37,550] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:34:37,685] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 01:08:12,229] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 01:08:12,241] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 01:08:12,242] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:08:12,242] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 01:08:12,243] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:08:12,257] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:00:00+00:00
[2023-07-26 01:08:12,261] {standard_task_runner.py:52} INFO - Started process 164 to run task
[2023-07-26 01:08:12,266] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpt4aexzq1', '--error-file', '/tmp/tmpx03r_lgd']
[2023-07-26 01:08:12,267] {standard_task_runner.py:80} INFO - Job 3: Subtask fetch_exchange_rates_task
[2023-07-26 01:08:12,353] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [running]> on host 4c9ca6074b1f
[2023-07-26 01:08:12,425] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:00:00+00:00
[2023-07-26 01:08:12,860] {logging_mixin.py:115} INFO - Save a new table exchange_latest_BTC.csv
[2023-07-26 01:08:12,885] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 89, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.UndefinedFile: could not open file "./csv_files/exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-07-26 01:08:12,893] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T000000, start_date=20230726T010812, end_date=20230726T010812
[2023-07-26 01:08:12,903] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task fetch_exchange_rates_task (could not open file "./csv_files/exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 164)
[2023-07-26 01:08:12,920] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 01:08:12,944] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 01:27:04,251] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 01:27:04,260] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 01:27:04,260] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:27:04,261] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 01:27:04,262] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:27:04,272] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:00:00+00:00
[2023-07-26 01:27:04,276] {standard_task_runner.py:52} INFO - Started process 74 to run task
[2023-07-26 01:27:04,279] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpif2yvl94', '--error-file', '/tmp/tmp9fo7l5mw']
[2023-07-26 01:27:04,281] {standard_task_runner.py:80} INFO - Job 3: Subtask fetch_exchange_rates_task
[2023-07-26 01:27:04,350] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [running]> on host 6e11a261c833
[2023-07-26 01:27:04,406] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:00:00+00:00
[2023-07-26 01:27:04,849] {logging_mixin.py:115} INFO - Save a new table exchange_latest_BTC.csv
[2023-07-26 01:27:04,877] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 89, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.UndefinedFile: could not open file "./docker-entrypoint-initdb.d/csv_files/exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-07-26 01:27:04,886] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T000000, start_date=20230726T012704, end_date=20230726T012704
[2023-07-26 01:27:04,897] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task fetch_exchange_rates_task (could not open file "./docker-entrypoint-initdb.d/csv_files/exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 74)
[2023-07-26 01:27:04,934] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 01:27:04,963] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:03:15,942] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 05:03:15,982] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26 05:03:15,983] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:15,984] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:03:15,984] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:16,011] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:00:00+00:00
[2023-07-26 05:03:16,047] {standard_task_runner.py:52} INFO - Started process 224 to run task
[2023-07-26 05:03:16,070] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpwh776vd_', '--error-file', '/tmp/tmph19f3x_v']
[2023-07-26 05:03:16,078] {standard_task_runner.py:80} INFO - Job 18: Subtask fetch_exchange_rates_task
[2023-07-26 05:03:16,577] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:00:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:03:17,186] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:00:00+00:00
[2023-07-26 05:03:17,575] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:03:17,576] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:03:17,587] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:03:17,977] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:03:17,980] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:03:17,984] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:03:18,468] {logging_mixin.py:115} INFO - Save a new file exchange_latest_GBR.csv
[2023-07-26 05:03:18,475] {logging_mixin.py:115} INFO - Create a new table exchange_latest_GBR
[2023-07-26 05:03:18,483] {logging_mixin.py:115} INFO - Insert into table exchange_latest_GBR
[2023-07-26 05:03:18,932] {logging_mixin.py:115} INFO - Save a new file exchange_latest_JPY.csv
[2023-07-26 05:03:18,933] {logging_mixin.py:115} INFO - Create a new table exchange_latest_JPY
[2023-07-26 05:03:18,944] {logging_mixin.py:115} INFO - Insert into table exchange_latest_JPY
[2023-07-26 05:03:19,400] {logging_mixin.py:115} INFO - Save a new file exchange_latest_CNY.csv
[2023-07-26 05:03:19,405] {logging_mixin.py:115} INFO - Create a new table exchange_latest_CNY
[2023-07-26 05:03:19,420] {logging_mixin.py:115} INFO - Insert into table exchange_latest_CNY
[2023-07-26 05:03:19,442] {python.py:173} INFO - Done. Returned value was: None
[2023-07-26 05:03:19,756] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T000000, start_date=20230726T050315, end_date=20230726T050319
[2023-07-26 05:03:19,887] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-26 05:03:20,094] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
