[2023-07-26 23:54:13,875] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T03:30:00+00:00 [queued]>
[2023-07-26 23:54:13,896] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T03:30:00+00:00 [queued]>
[2023-07-26 23:54:13,897] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 23:54:13,898] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 23:54:13,899] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 23:54:13,926] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 03:30:00+00:00
[2023-07-26 23:54:13,938] {standard_task_runner.py:52} INFO - Started process 527 to run task
[2023-07-26 23:54:13,955] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T03:30:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpbz751yyf', '--error-file', '/tmp/tmpke9229oj']
[2023-07-26 23:54:13,960] {standard_task_runner.py:80} INFO - Job 76: Subtask fetch_exchange_rates_task
[2023-07-26 23:54:14,263] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T03:30:00+00:00 [running]> on host 43d0198bb36a
[2023-07-26 23:54:14,598] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T03:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T03:30:00+00:00
[2023-07-26 23:54:14,994] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 23:54:14,995] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 23:54:15,003] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 23:54:15,366] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 23:54:15,367] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 23:54:15,375] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 23:54:15,398] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "99,720681"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,720681"

[2023-07-26 23:54:15,421] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T033000, start_date=20230726T235413, end_date=20230726T235415
[2023-07-26 23:54:15,467] {standard_task_runner.py:97} ERROR - Failed to execute job 76 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "99,720681"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,720681"
; 527)
[2023-07-26 23:54:15,563] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 23:54:15,710] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
