[2023-07-26 04:18:16,224] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [queued]>
[2023-07-26 04:18:16,341] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [queued]>
[2023-07-26 04:18:16,355] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 04:18:16,361] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 04:18:16,362] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 04:18:16,452] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-26 01:20:00+00:00
[2023-07-26 04:18:16,520] {standard_task_runner.py:52} INFO - Started process 7060 to run task
[2023-07-26 04:18:16,574] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-26T01:20:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpmzc_awvh', '--error-file', '/tmp/tmp618tl8zm']
[2023-07-26 04:18:16,588] {standard_task_runner.py:80} INFO - Job 55: Subtask fetch_exchange_rates_task
[2023-07-26 04:18:16,831] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [running]> on host 6e11a261c833
[2023-07-26 04:18:17,072] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T01:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-26T01:20:00+00:00
[2023-07-26 04:18:17,531] {logging_mixin.py:115} INFO - Save a new table exchange_latest_BTC.csv
[2023-07-26 04:18:17,531] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC.csv
[2023-07-26 04:18:17,537] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC.csv
[2023-07-26 04:18:17,934] {logging_mixin.py:115} INFO - Save a new table exchange_latest_EUR.csv
[2023-07-26 04:18:17,963] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR.csv
[2023-07-26 04:18:17,981] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR.csv
[2023-07-26 04:18:18,031] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "99,603666"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,603666"

[2023-07-26 04:18:18,098] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230726T012000, start_date=20230726T041816, end_date=20230726T041818
[2023-07-26 04:18:18,303] {standard_task_runner.py:97} ERROR - Failed to execute job 55 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "99,603666"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,603666"
; 7060)
[2023-07-26 04:18:18,403] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 04:18:18,766] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:07:42,970] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [queued]>
[2023-07-26 05:07:43,022] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [queued]>
[2023-07-26 05:07:43,023] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:07:43,032] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:07:43,035] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:07:43,182] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-26 01:20:00+00:00
[2023-07-26 05:07:43,199] {standard_task_runner.py:52} INFO - Started process 2132 to run task
[2023-07-26 05:07:43,234] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-26T01:20:00+00:00', '--job-id', '555', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpor2gg9_l', '--error-file', '/tmp/tmplnvh2pa8']
[2023-07-26 05:07:43,239] {standard_task_runner.py:80} INFO - Job 555: Subtask fetch_exchange_rates_task
[2023-07-26 05:07:43,567] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-26T01:20:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:07:44,188] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T01:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-26T01:20:00+00:00
[2023-07-26 05:07:44,837] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:07:44,838] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:07:44,895] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:07:45,583] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:07:45,708] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:07:45,813] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:07:46,493] {logging_mixin.py:115} INFO - Save a new file exchange_latest_GBR.csv
[2023-07-26 05:07:46,516] {logging_mixin.py:115} INFO - Create a new table exchange_latest_GBR
[2023-07-26 05:07:46,526] {logging_mixin.py:115} INFO - Insert into table exchange_latest_GBR
[2023-07-26 05:07:47,137] {logging_mixin.py:115} INFO - Save a new file exchange_latest_JPY.csv
[2023-07-26 05:07:47,152] {logging_mixin.py:115} INFO - Create a new table exchange_latest_JPY
[2023-07-26 05:07:47,329] {logging_mixin.py:115} INFO - Insert into table exchange_latest_JPY
[2023-07-26 05:07:47,926] {logging_mixin.py:115} INFO - Save a new file exchange_latest_CNY.csv
[2023-07-26 05:07:47,931] {logging_mixin.py:115} INFO - Create a new table exchange_latest_CNY
[2023-07-26 05:07:47,973] {logging_mixin.py:115} INFO - Insert into table exchange_latest_CNY
[2023-07-26 05:07:48,031] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_cny, line 3, column exchange_rate: "2023-07-26"

[2023-07-26 05:07:48,077] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230726T012000, start_date=20230726T050742, end_date=20230726T050748
[2023-07-26 05:07:48,333] {standard_task_runner.py:97} ERROR - Failed to execute job 555 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_cny, line 3, column exchange_rate: "2023-07-26"
; 2132)
[2023-07-26 05:07:48,554] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-07-26 05:07:48,586] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 2132. PIDs of all processes in the group: [2132]
[2023-07-26 05:07:48,588] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 2132
[2023-07-26 05:07:48,598] {process_utils.py:75} INFO - Process psutil.Process(pid=2132, status='terminated', exitcode=1, started='05:07:42') (2132) terminated with exit code 1
