[2023-07-25 20:38:32,334] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T14:30:00+00:00 [queued]>
[2023-07-25 20:38:32,355] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T14:30:00+00:00 [queued]>
[2023-07-25 20:38:32,359] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:32,363] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:32,364] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:32,395] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 14:30:00+00:00
[2023-07-25 20:38:32,406] {standard_task_runner.py:52} INFO - Started process 9248 to run task
[2023-07-25 20:38:32,426] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T14:30:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpoihfbztg', '--error-file', '/tmp/tmp5j84sole']
[2023-07-25 20:38:32,432] {standard_task_runner.py:80} INFO - Job 185: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:32,598] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T14:30:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:32,761] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T14:30:00+00:00
[2023-07-25 20:38:34,264] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:34,273] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T143000, start_date=20230725T203832, end_date=20230725T203834
[2023-07-25 20:38:34,282] {standard_task_runner.py:97} ERROR - Failed to execute job 185 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9248)
[2023-07-25 20:38:34,317] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:34,346] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
