[2023-07-25 20:34:54,449] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T20:34:51.005737+00:00 [queued]>
[2023-07-25 20:34:54,486] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T20:34:51.005737+00:00 [queued]>
[2023-07-25 20:34:54,487] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:54,488] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:34:54,489] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:54,549] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 20:34:51.005737+00:00
[2023-07-25 20:34:54,572] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'manual__2023-07-25T20:34:51.005737+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpgp09sb2y', '--error-file', '/tmp/tmpkgv7k4g0']
[2023-07-25 20:34:54,568] {standard_task_runner.py:52} INFO - Started process 8875 to run task
[2023-07-25 20:34:54,582] {standard_task_runner.py:80} INFO - Job 118: Subtask fetch_exchange_rates_task
[2023-07-25 20:34:54,739] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T20:34:51.005737+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:34:54,925] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T20:34:51.005737+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-25T20:34:51.005737+00:00
[2023-07-25 20:34:56,462] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:34:56,471] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T203451, start_date=20230725T203454, end_date=20230725T203456
[2023-07-25 20:34:56,482] {standard_task_runner.py:97} ERROR - Failed to execute job 118 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 8875)
[2023-07-25 20:34:56,504] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:34:56,534] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
