[2023-07-25 22:47:25,464] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T22:47:24.032331+00:00 [queued]>
[2023-07-25 22:47:25,477] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T22:47:24.032331+00:00 [queued]>
[2023-07-25 22:47:25,477] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:47:25,478] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 22:47:25,478] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:47:25,491] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 22:47:24.032331+00:00
[2023-07-25 22:47:25,495] {standard_task_runner.py:52} INFO - Started process 235 to run task
[2023-07-25 22:47:25,498] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'manual__2023-07-25T22:47:24.032331+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpu32cup28', '--error-file', '/tmp/tmp53eebens']
[2023-07-25 22:47:25,500] {standard_task_runner.py:80} INFO - Job 319: Subtask fetch_exchange_rates_task
[2023-07-25 22:47:25,564] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task manual__2023-07-25T22:47:24.032331+00:00 [running]> on host 661c8d62a693
[2023-07-25 22:47:25,616] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T22:47:24.032331+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-25T22:47:24.032331+00:00
[2023-07-25 22:47:25,997] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 92, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.UndefinedFile: could not open file "exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-07-25 22:47:26,006] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T224724, start_date=20230725T224725, end_date=20230725T224726
[2023-07-25 22:47:26,013] {standard_task_runner.py:97} ERROR - Failed to execute job 319 for task fetch_exchange_rates_task (could not open file "exchange_latest_BTC.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 235)
[2023-07-25 22:47:26,033] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 22:47:26,055] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
